id: IE1E66A73
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:55:12+00:00'
last_modified: '2022-06-08T11:11:36.509362+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7997
  title: འཇིགས་མེད་ཕུན་ཚོགས་འབྱུང་གནས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    FA44:
      image_group_id: I3CN7999
      title: ''
      total_pages: 132
      order: 1
      base_file: FA44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
