id: P009459
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:39:47.147021
source_metadata:
  id: bdr:W3CN7997
  title: འཇིགས་མེད་ཕུན་ཚོགས་འབྱུང་གནས།
  author: ''
  volumes:
    9efc5af420fe4719ac6981bf69427c8d:
      image_group_id: I3CN7999
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
